env:
  es2020: true
settings:
  react:
    version: 16.13.1
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  'indent': 
    - error
    - 2
    - SwitchCase: 1
  '@typescript-eslint/explicit-module-boundary-types': 
    off
  '@typescript-eslint/no-unused-vars':
    - 1
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_    
  'max-len': 
    - 0
    - ignoreUrls: true
      code: 80
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
overrides:
  - files:
      - '*.ts'
    rules:
      '@typescript-eslint/explicit-module-boundary-types':
        - error
